In [47]:
import numpy as np


In [48]:
#converting list to array datatype using numpy library
lst=[2,6,1,5]
arr=np.array(lst)
print(type(arr))

<class 'numpy.ndarray'>


In [49]:
# multidimentional array 
lst1=[1,2,3,4,5]
lst2=[5,6,7,8,9]
lst3=[11,12,13,14,15]
arr=np.array([lst1,lst2,lst3])

In [50]:
#indexing of array

arr.shape
arr[1,3]
#changing the element of an array
arr[2,4]=16
arr


array([[ 1,  2,  3,  4,  5],
       [ 5,  6,  7,  8,  9],
       [11, 12, 13, 14, 16]])

In [51]:

arr[0:2,2:4]                      #array[row,column]

array([[3, 4],
       [7, 8]])

In [52]:
#EDA condition
#to check the condition
arr<4

array([[ True,  True,  True, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [53]:
arr[arr<4]

array([1, 2, 3])

In [54]:
#to reshape the elemnts of an array
arr.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  5],
       [ 6,  7,  8],
       [ 9, 11, 12],
       [13, 14, 16]])

In [55]:
#arranging the elements
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [56]:
np.arange(1,20,2).reshape(5,2,1)

array([[[ 1],
        [ 3]],

       [[ 5],
        [ 7]],

       [[ 9],
        [11]],

       [[13],
        [15]],

       [[17],
        [19]]])

In [57]:
#multiplication of two array returns the sqaure of respective elements
list1=[1,2,3,4,5]
arr2=np.array(list1)
arr2*arr2

array([ 1,  4,  9, 16, 25])

In [58]:
arr*arr

array([[  1,   4,   9,  16,  25],
       [ 25,  36,  49,  64,  81],
       [121, 144, 169, 196, 256]])

In [59]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [60]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [61]:
#gives the random number between 2 numbers
np.random.randint(5,3100,4)

array([ 547, 2964, 2149,   81], dtype=int32)

In [62]:

np.random.randn(1,2)

array([[-1.29508924, -2.22229804]])

In [63]:
# np.tile(array, (rows, cols)) 
# repeats the small array across dimensions.
# The first number (3) is how many times you want to repeat the array along the rows.
# The second number (2) is how many times you want to repeat it along the columns.
# 1-dimensional array
lst1=[1,2,3]
arr1=np.array(lst1)
repeated_arr=np.tile(arr1,(3))
repeated_arr


array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [64]:
# 2-dimensional array
lst2=[[1,2],[3,4]]
arr=np.array(lst)
repeated_arr=np.tile(arr,(2,3))
repeated_arr

array([[2, 6, 1, 5, 2, 6, 1, 5, 2, 6, 1, 5],
       [2, 6, 1, 5, 2, 6, 1, 5, 2, 6, 1, 5]])

In [65]:
#Generating an array with element indexes using .arrange() function such that the array elements appear in ascending order and resha[ing using .reshape function()
arr=np.arange(1,13,1).reshape(3,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])